name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
#    - name: Install Google Chrome # Using shell script to install Google Chrome
#      run: |
#        chmod +x ./scripts/InstallChrome.sh
#                    ./scripts/InstallChrome.sh
#    - name: Set up virtual X11
#      run: sudo apt-get install xvfb
#    - name: Start virtual frame buffer
#      run: Xvfb :19 -screen 0 1024x768x16 &

    - name: Cache Maven packages
      uses: actions/cache@v1
      with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: xvfb-run mvn -B package --file pom.xml
      env:
        DISPLAY: 19
